### ISSUE TITLE
isSelected doesn't work

### ISSUE THREAD

**Issue by SaptakS** [naadydev/jTLine#1]
The isSelected attribute is not functional since according to the code, always the 1st point is selected by default. This can be fixed using the isSelectedAttr property that is declared in the default or if none of the points have isSelected set, then we can make the first point as selected.

**Comment by SaptakS** [comment]
I can provide the fix for this.

**Comment by naadydev** [comment]
Hi SaptakS , Many thanks 
I added you as a repository collaborator, you can fix it.

**Comment by SaptakS** [comment]
@naadydev fixed in https://github.com/naadydev/jTLine/commit/fd50dd8ad3218d0b1341b57730d8523d06604d9b
